3_Implementation/WebAPI/WebAPI/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('image_process.urls'))
]

3_Implementation/WebAPI/image_process/urls.py
from django.urls import path

from . import views

app_name = 'detector_app'

urlpatterns = [
    path('',views.index,name='index')
]

3_Implementation/WebAPI/image_process/models.py
from django.db import models

# Create your models here.

3_Implementation/WebAPI/image_process/views.py
from django.shortcuts import render
from django.http import  HttpResponse, HttpResponseRedirect
import cv2
import numpy as np
from PIL import Image
from django.views.decorators.csrf import csrf_exempt
from YOLOv3 import yolo_detector
# Create your views here.
@csrf_exempt

def index(request):
    if request.method == 'GET':
        return render(request,'image_process/form.html')
    if request.method == 'POST':
        content = 'image/png'
        response = HttpResponse(content_type=content)
        image = request.FILES['image'].read()
        image = np.asarray(bytearray(image), dtype="uint8")
        image = cv2.imdecode(image, cv2.IMREAD_COLOR)
        image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
        image = yolo_detector.Object_Detection(image)
        final = Image.fromarray(image)
        final.save(response,"png")
        return response

3_Implementation/WebAPI/image_process/templates/image_process/form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Upload Image</title>
</head>
<body>
    <form action="{% url 'detector_app:index' %}" enctype="multipart/form-data" method="POST">
        <input type="file" name="image">
        <input type = "submit" name = "submit" value="Submit">
    </form>
</body>
</html>